#!/bin/bash

boot='ext2'
racine='ext4'
home='ext4'

# Pour le choix du système de fichier sur les partition
echo '========================================================'
echo '=         Choix de système de fichier proposé          ='
echo '========================================================'
echo ':: Le choix du système de fichier pour /boot est  : '$boot
echo ':: Le choix du système de fichier pour / est      : '$racine
echo ':: Le choix du système de fichier pour /home est  : '$home
echo '========================================================'
echo '=  Choix Ok = Entrée ---  sinon  Ctrl + c pour Quitter ='
read -p '========================================================'

mkfs.$boot /dev/sda1
mkfs.$racine /dev/sda3
mkfs.$home /dev/sda4

# La swap est créée en utilisant mkswap : 
mkswap /dev/sda2

echo ':: Les 4 partitions sont crées ::'
echo ':: /dev/sda1 (/boot) est formaté en : '$boot
echo ':: /dev/sda2 (swap) est formaté en :  swap'
echo ':: /dev/sda3 (/) est formaté en :     '$racine
echo ':: /dev/sda4 (/home) est formaté en : '$home
echo '==================================================='
echo '==================================================='

# Montage des partitions
echo ':: Montage des partitions ::'
mount /dev/sda3 /mnt
swapon /dev/sda2
mkdir /mnt/home && mount /dev/sda4 /mnt/home
mkdir /mnt/boot && mount /dev/sda1 /mnt/boot
echo ':: Les 4 partitions sont montées ::'
echo '==================================================='
echo '= Système de fichiers créés et partitions montées ='
echo '==================================================='

