#!/bin/bash
#
# 07_install_part2.sh
# 
# Jean-Pierre Antinoux - janvier 2018

CWD=$(pwd)
# Vérification de la syntaxe de l'utilisateur principal
if [ $USER != "root" ]
    then
        echo "Pour exécuter ce script il faut être l'utilisateur root !"
    else
    # Création d'un utilisateur
    read -p 'Utilisateur (login) à créer : ' nom
    while [ -z $nom ]; do
    echo "Veuillez saisir votre nom"
    read nom
    	done

    dhcpcd enp0s
    sleep 5 
    systemctl start dhcpcd
    sleep 2 
    systemctl enable dhcpcd
    sleep 3

    pacman -Syu
    sleep 2 
    pacman -S networkmanager network-manager-applet
    systemctl enable NetworkManager.service
    systemctl start NetworkManager.service
    sleep 2 
    pacman -S yaourt
    sleep 2 
    yaourt -S alsa-utils alsa-oss pulseaudio-equalizer
    sleep 2 
    yaourt -S xorg-server xorg-xinit
    sleep 2
    # Création du nom et avec le groupe users
    echo ":: Création du nom ::"
		useradd -g users -G users -m $nom
   
		# Création du mot de passe
		echo ":: Création du mot de passe ::"
		passwd $nom

		# Ajouter les groupes courant
		echo ":: Ajout de groupes courant ::"
		usermod -aG audio,log,lp,optical,scanner,storage,video $nom
    
		# Affichag des groupes créés
		echo ":: Liste des groupes de $nom ::"
		groups $nom
    sleep 2
    yaourt -S mate mate-extra gvfs gvfs-smb xdg-user-dirs
    sleep 2 
    cp $CWD../xinit/xinitrc-mate /home/$nom/.xinitrc
    sleep 2 
		pacman -S lxdm
    sleep 2 
		cp $CWD../pam/lxdm /etc/pam.d/lxdm
    sleep 2   
		alsamixer
    aplay /usr/share/sounds/alsa/*.wav
		sleep 2
    alasctl store
		sleep 2
    systemctl start lxdm
fi

exit 0
